# Bloc 3 — Transformations & Feature Engineering
Objectifs: créer des colonnes calculées, transformer les types, manipuler les chaînes (.str), manipuler les dates (.dt), trier

In [1]:
import numpy as np
import pandas as pd

In [3]:
products = pd.read_csv('../01_data/raw/thelook_products.csv')
sales = pd.read_csv('../01_data/exercises/thelook_sales.csv')
orders = pd.read_csv('../01_data/raw/thelook_orders.csv')

## 1. Ajouter et modifier des colonnes
On travaille souvent avec des colonnes qui n'existent pas encore dans le dataset. Il faut les créer.

### Créer une colonne calculée

In [4]:
products['marge'] = products['retail_price'] - products['cost']

# la nouvelle colonne apparait à droite
products.head()

,id,name,category,brand,department,cost,retail_price,sku,distribution_center_id,marge
0,1,Tommy Hilfiger Regular Fit Underwear,Underwear,Tommy Hilfiger,Women,6.57,10.31,SKU-00001,5,3.74
1,2,Hurley Pro Shorts,Shorts,Hurley,Women,20.85,37.55,SKU-00002,6,16.70
2,3,Columbia Sport Tops & Tees,Tops & Tees,Columbia,Men,21.34,44.52,SKU-00003,9,23.18
3,4,Volcom Classic Leggings,Leggings,Volcom,Women,14.98,42.24,SKU-00004,2,27.26
4,5,Hurley Urban Outerwear & Coats,Outerwear & Coats,Hurley,Women,89.58,149.11,SKU-00005,5,59.53

### Renommer ajouter et supprimer des colonnes

In [5]:
# imaginer que le nom des colomnes n'arriveront jamais bien formatés. 
# Une bonne pratique en base de donné et dataset est d'utiliser le snake_case
products = products.rename(columns={'retail_price': 'retail_price_euro'})
products = products.rename(columns={'sku': 'reference'})
products.head()

,id,name,category,brand,department,cost,retail_price_euro,reference,distribution_center_id,marge
0,1,Tommy Hilfiger Regular Fit Underwear,Underwear,Tommy Hilfiger,Women,6.57,10.31,SKU-00001,5,3.74
1,2,Hurley Pro Shorts,Shorts,Hurley,Women,20.85,37.55,SKU-00002,6,16.70
2,3,Columbia Sport Tops & Tees,Tops & Tees,Columbia,Men,21.34,44.52,SKU-00003,9,23.18
3,4,Volcom Classic Leggings,Leggings,Volcom,Women,14.98,42.24,SKU-00004,2,27.26
4,5,Hurley Urban Outerwear & Coats,Outerwear & Coats,Hurley,Women,89.58,149.11,SKU-00005,5,59.53

In [6]:
# Mais il vous sera aussi nécessaire de créer vos propres colonnes
# Ici, on change également le type
products['ref_id'] = products['reference'] + products['id'].astype(str)
products.info()

# Pourquoi doit-on caster le type de la colonne ['id']? 
# Essayer sans pour voir...

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      2000 non-null   int64
 1   name                    2000 non-null   str
 2   category                2000 non-null   str
 3   brand                   2000 non-null   str
 4   department              2000 non-null   str
 5   cost                    2000 non-null   float64
 6   retail_price_euro       2000 non-null   float64
 7   reference               2000 non-null   str
 8   distribution_center_id  2000 non-null   int64
 9   marge                   2000 non-null   float64
 10  ref_id                  2000 non-null   str
dtypes: float64(3), int64(2), str(6)
memory usage: 172.0 KB

In [7]:
# Il peut aussi arriver que vous deviez supprimer des colonnes inutiles ou pour créer un dataset alternatif
products = products.drop(columns=['brand'])
products.head()

,id,name,category,department,cost,retail_price_euro,reference,distribution_center_id,marge,ref_id
0,1,Tommy Hilfiger Regular Fit Underwear,Underwear,Women,6.57,10.31,SKU-00001,5,3.74,SKU-000011
1,2,Hurley Pro Shorts,Shorts,Women,20.85,37.55,SKU-00002,6,16.70,SKU-000022
2,3,Columbia Sport Tops & Tees,Tops & Tees,Men,21.34,44.52,SKU-00003,9,23.18,SKU-000033
3,4,Volcom Classic Leggings,Leggings,Women,14.98,42.24,SKU-00004,2,27.26,SKU-000044
4,5,Hurley Urban Outerwear & Coats,Outerwear & Coats,Women,89.58,149.11,SKU-00005,5,59.53,SKU-000055

In [8]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      2000 non-null   int64
 1   name                    2000 non-null   str
 2   category                2000 non-null   str
 3   department              2000 non-null   str
 4   cost                    2000 non-null   float64
 5   retail_price_euro       2000 non-null   float64
 6   reference               2000 non-null   str
 7   distribution_center_id  2000 non-null   int64
 8   marge                   2000 non-null   float64
 9   ref_id                  2000 non-null   str
dtypes: float64(3), int64(2), str(5)
memory usage: 156.4 KB

### Mini-exercice : à vous !

In [10]:
# Créez une colonne 'taux_marge' = marge / retail_price * 100
products['taux_marge'] = products['marge'] / products['retail_price_euro'] * 100

# Affichez les 3 premières lignes

print(products.head(3))

   id                                  name     category department   cost  \
0   1  Tommy Hilfiger Regular Fit Underwear    Underwear      Women   6.57
1   2                     Hurley Pro Shorts       Shorts      Women  20.85
2   3            Columbia Sport Tops & Tees  Tops & Tees        Men  21.34

   retail_price_euro  reference  distribution_center_id  marge      ref_id  \
0              10.31  SKU-00001                       5   3.74  SKU-000011
1              37.55  SKU-00002                       6  16.70  SKU-000022
2              44.52  SKU-00003                       9  23.18  SKU-000033

   taux_marge
0   36.275461
1   44.474035
2   52.066487

## 2. Transformer les types (dtypes)
Quand on charge un CSV, pandas devine les types. Parfois il se trompe. Il faut savoir corriger.

### Vérifier les types actuels

In [ ]:
# Que remarquez-vous sur created_at ?
print(orders.dtypes)

### Convertir avec .astype()

Nous avons vu précédemment que Python possède ses propres fonction pour changer le type de data dúne variable.Pandas a sa propre méthode pour se faire: `.astype()`

In [60]:
print("Avant :", products['id'].dtype)
products['id'] = products['id'].astype(str)
print("Après :", products['id'].dtype)

Avant : int64
Après : str

### Forcer la conversion numérique : pd.to_numeric()

In [63]:
s = pd.Series(['10', '20', 'oops', '40'])
s.info()

<class 'pandas.Series'>
RangeIndex: 4 entries, 0 to 3
Series name: None
Non-Null Count  Dtype
--------------  -----
4 non-null      str
dtypes: str(1)
memory usage: 164.0 bytes

In [71]:
# Pour transformer nos strings, on utilise la fonction pd.to_numeric()
# errors='coerce' transforme les erreurs en NaN au lieu de planter
s_numeric = pd.to_numeric(s, errors='coerce')
s_numeric

0        6.57
1       20.85
2       21.34
3       14.98
4       89.58
        ...
1995     3.78
1996    21.10
1997    20.76
1998    25.23
1999    23.36
Name: cost, Length: 2000, dtype: float64

### Convertir les dates : pd.to_datetime()

In [78]:
# On va utiliser ici le dataset `orders` que vous avez chargé plus tôt.
# Observons son data type:

#orders.

# Quel est le type de delivered_at? returned_at?

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      20000 non-null  int64
 1   user_id       20000 non-null  int64
 2   status        20000 non-null  str
 3   created_at    20000 non-null  str
 4   num_of_item   20000 non-null  int64
 5   shipped_at    16800 non-null  str
 6   delivered_at  14361 non-null  str
 7   returned_at   1388 non-null   str
dtypes: int64(3), str(5)
memory usage: 1.2 MB

In [114]:
# Ceci est un cas typique où vous aurez des datetime ou des timestamps qui arriveront sous forme d'objets ou string.
orders['created_at'] = pd.to_datetime(orders['created_at'])

print(orders['created_at'].dtype)  # on doit trouver: datetime64
orders.info()

datetime64[us]
<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      20000 non-null  int64
 1   user_id       20000 non-null  int64
 2   status        20000 non-null  str
 3   created_at    20000 non-null  datetime64[us]
 4   num_of_item   20000 non-null  int64
 5   shipped_at    16800 non-null  str
 6   delivered_at  14361 non-null  str
 7   returned_at   1388 non-null   str
dtypes: datetime64[us](1), int64(3), str(4)
memory usage: 1.2 MB

## 3. Manipuler le texte avec .str
Pandas offre un accesseur `.str` qui permet d'appliquer des opérations texte à toute une colonne d'un coup.

### Changer le format

In [81]:
# tout en minuscules, le plus souvent utilisé dans le code. Qui aime se faire hurler dessus en capitale par son code?
lower = products['name'].str.lower().head(3)
lower

0    tommy hilfiger regular fit underwear
1                       hurley pro shorts
2              columbia sport tops & tees
Name: name, dtype: str

In [84]:
# ici en MAJUSCULE
upper = products['name'].str.upper().head(3)
upper

0    TOMMY HILFIGER REGULAR FIT UNDERWEAR
1                       HURLEY PRO SHORTS
2              COLUMBIA SPORT TOPS & TEES
Name: name, dtype: str

In [82]:
# Et Là ?
title = products['name'].str.title().head(3)
title

0    Tommy Hilfiger Regular Fit Underwear
1                       Hurley Pro Shorts
2              Columbia Sport Tops & Tees
Name: name, dtype: str

### Chercher dans le texte

In [108]:
# Combien de produits contiennent le mot 'Slim' ?
slim = products['name'].str.contains(('Slim'), na=False)
print(slim.sum())

# Et si je ne sais pas si j'ai SLIM, Slim, ou slim ?

161

### Nettoyer le texte

In [112]:
# Explique que fait on ici:
nettoye = products['name'].str.strip().str.replace('  ', '')
nettoye.head()

0    Tommy Hilfiger Regular Fit Underwear
1                       Hurley Pro Shorts
2              Columbia Sport Tops & Tees
3                 Volcom Classic Leggings
4          Hurley Urban Outerwear & Coats
Name: name, dtype: str

## 4. Manipuler les dates avec .dt

### Extraire les composantes d'une date
Par défaut, lors de la lecture d'un fichier (ex: CSV), Pandas importe les dates sous forme de simples chaînes de caractères (object ou str).

Sous forme de texte, vous ne pouvez pas:
- effectuer de calculs temporels 
- extraire facilement des composants de date (example: jour, mois etc...)

Une fois la colonne convertie en datetime, on peut en extraire plein d'informations.

In [118]:
# Chaque composante devient une nouvelle colonne utilisable pour l'analyse

orders['annee'] = orders['created_at'].dt.year
orders['mois'] = orders['created_at'].dt.month
orders['jour_semaine'] = orders['created_at'].dt.day_name()
orders.head()

,order_id,user_id,status,created_at,num_of_item,shipped_at,delivered_at,returned_at,annee,mois,jour_semaine
0,1,405,Complete,2023-03-15 00:52:04,2,2023-03-17 00:52:04,2023-03-25 00:52:04,NaN,2023,3,Wednesday
1,2,1792,Complete,2024-06-29 13:30:52,3,2024-07-02 13:30:52,2024-07-05 13:30:52,NaN,2024,6,Saturday
2,3,2908,Complete,2024-02-17 14:38:01,1,2024-02-19 14:38:01,2024-02-28 14:38:01,NaN,2024,2,Saturday
3,4,370,Processing,2024-08-01 21:04:12,2,NaN,NaN,NaN,2024,8,Thursday
4,5,97,Returned,2023-12-23 09:01:16,3,2023-12-24 09:01:16,2023-12-31 09:01:16,2024-01-23 09:01:16,2023,12,Saturday

In [120]:
# Vérifiez le type des nouvelles colonnes créées
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      20000 non-null  int64
 1   user_id       20000 non-null  int64
 2   status        20000 non-null  str
 3   created_at    20000 non-null  datetime64[us]
 4   num_of_item   20000 non-null  int64
 5   shipped_at    16800 non-null  str
 6   delivered_at  14361 non-null  str
 7   returned_at   1388 non-null   str
 8   annee         20000 non-null  int32
 9   mois          20000 non-null  int32
 10  jour_semaine  20000 non-null  str
dtypes: datetime64[us](1), int32(2), int64(3), str(5)
memory usage: 1.5 MB

### Calculer un écart entre deux dates

In [121]:
# Rappel de conversion str -> datetime type
orders['shipped_at'] = pd.to_datetime(orders['shipped_at'])

# Le résultat est un timedelta, .dt.days donne le nombre de jours
# on peut utiliser de simple operator comme '-' ou '+'
orders['delai'] = (orders['shipped_at'] - orders['created_at']).dt.days

orders[['created_at', 'shipped_at', 'delai']].head()

           created_at          shipped_at  delai
0 2023-03-15 00:52:04 2023-03-17 00:52:04    2.0
1 2024-06-29 13:30:52 2024-07-02 13:30:52    3.0
2 2024-02-17 14:38:01 2024-02-19 14:38:01    2.0
3 2024-08-01 21:04:12                 NaT    NaN
4 2023-12-23 09:01:16 2023-12-24 09:01:16    1.0

# Quel est le délai de livraison moyen ? Testez avec .mean()

In [ ]:
delai_moyen = orders['delai']."METHODE"()
print(delai_moyen)

## 5. Trier les données

### Trier par valeurs

In [122]:
# Selon vous, que fait cette fonction? A quoi correspond l'argument 'ascending'
products.sort_values('retail_price', ascending=False).head(10)

,id,name,category,brand,department,cost,retail_price,sku,distribution_center_id
1493,1494,Hurley Essential Suits & Sport Coats,Suits & Sport Coats,Hurley,Women,198.17,512.19,SKU-01494,5
1787,1788,Dockers Premium Suits & Sport Coats,Suits & Sport Coats,Dockers,Men,168.68,484.08,SKU-01788,5
600,601,Levi's Classic Suits & Sport Coats,Suits & Sport Coats,Levi's,Men,194.24,472.27,SKU-00601,8
1247,1248,BCBGMAXAZRIA Sport Suits & Sport Coats,Suits & Sport Coats,BCBGMAXAZRIA,Men,171.50,468.52,SKU-01248,8
298,299,Allegra K Vintage Suits & Sport Coats,Suits & Sport Coats,Allegra K,Men,191.39,462.85,SKU-00299,9
1977,1978,Diesel Modern Suits & Sport Coats,Suits & Sport Coats,Diesel,Men,172.04,461.81,SKU-01978,1
1489,1490,Tommy Hilfiger Original Suits & Sport Coats,Suits & Sport Coats,Tommy Hilfiger,Men,168.12,454.79,SKU-01490,10
142,143,Levi's Sport Suits & Sport Coats,Suits & Sport Coats,Levi's,Men,153.02,446.66,SKU-00143,9
440,441,True Religion Regular Fit Suits & Sport Coats,Suits & Sport Coats,True Religion,Men,167.97,446.63,SKU-00441,2
1641,1642,Volcom Classic Suits & Sport Coats,Suits & Sport Coats,Volcom,Women,164.37,432.68,SKU-01642,6

### Trier par plusieurs colonnes

In [123]:
products.sort_values(['department', 'retail_price'], ascending=[True, False]).head(10)

,id,name,category,brand,department,cost,retail_price,sku,distribution_center_id
1787,1788,Dockers Premium Suits & Sport Coats,Suits & Sport Coats,Dockers,Men,168.68,484.08,SKU-01788,5
600,601,Levi's Classic Suits & Sport Coats,Suits & Sport Coats,Levi's,Men,194.24,472.27,SKU-00601,8
1247,1248,BCBGMAXAZRIA Sport Suits & Sport Coats,Suits & Sport Coats,BCBGMAXAZRIA,Men,171.50,468.52,SKU-01248,8
298,299,Allegra K Vintage Suits & Sport Coats,Suits & Sport Coats,Allegra K,Men,191.39,462.85,SKU-00299,9
1977,1978,Diesel Modern Suits & Sport Coats,Suits & Sport Coats,Diesel,Men,172.04,461.81,SKU-01978,1
1489,1490,Tommy Hilfiger Original Suits & Sport Coats,Suits & Sport Coats,Tommy Hilfiger,Men,168.12,454.79,SKU-01490,10
142,143,Levi's Sport Suits & Sport Coats,Suits & Sport Coats,Levi's,Men,153.02,446.66,SKU-00143,9
440,441,True Religion Regular Fit Suits & Sport Coats,Suits & Sport Coats,True Religion,Men,167.97,446.63,SKU-00441,2
211,212,Hurley Slim Fit Outerwear & Coats,Outerwear & Coats,Hurley,Men,141.69,413.60,SKU-00212,9
212,213,Volcom Slim Fit Outerwear & Coats,Outerwear & Coats,Volcom,Men,147.98,404.95,SKU-00213,3

### Réinitialiser l'index

In [124]:
# Après un tri ou un filtre, l'index est désorganisé. reset_index le remet à 0, 1, 2...
produits_tries = products.sort_values('retail_price', ascending=False)
produits_tries.reset_index(drop=True).head()

,id,name,category,brand,department,cost,retail_price,sku,distribution_center_id
0,1494,Hurley Essential Suits & Sport Coats,Suits & Sport Coats,Hurley,Women,198.17,512.19,SKU-01494,5
1,1788,Dockers Premium Suits & Sport Coats,Suits & Sport Coats,Dockers,Men,168.68,484.08,SKU-01788,5
2,601,Levi's Classic Suits & Sport Coats,Suits & Sport Coats,Levi's,Men,194.24,472.27,SKU-00601,8
3,1248,BCBGMAXAZRIA Sport Suits & Sport Coats,Suits & Sport Coats,BCBGMAXAZRIA,Men,171.50,468.52,SKU-01248,8
4,299,Allegra K Vintage Suits & Sport Coats,Suits & Sport Coats,Allegra K,Men,191.39,462.85,SKU-00299,9

---
# Exercices pratiques

## Exercice 3.1 — L'Ingénieur de Features

### Questions
- Comment définissez vous le terme "features" ?
- Citez au moins 2 examples de features dont vous pouvez vous servir lors de la manipulation d'un dataset

### Pratique
Chargez `../01_data/exercises/thelook_sales.csv`. Créez ces colonnes:
1. `marge` = sale_price - cost
2. `mois` extrait de created_at (convertissez d'abord en datetime)
3. `is_premium` = True si sale_price > 100
4. `taux_marge` = (marge / sale_price) * 100

In [ ]:
# Une feature 

#

In [32]:
# 1. Chargez le fichier et créez les colonnes marge et taux_marge
sales = pd.read_csv('../01_data/exercises/thelook_sales.csv')
print(sales)
sales['marge'] = sales['sale_price'] - sales['cost']

          id  order_id  user_id  product_id  sale_price    status  \
0          1      2006     3641         533       37.47  Complete
1          2     19606     4289        1234       41.01  Complete
2          3     14234      973         409       15.67  Complete
3          4     14616     2136          67       75.15  Complete
4          5      7423     4007        1882       18.20  Complete
...      ...       ...      ...         ...         ...       ...
49995  49996     18636     1560         560       33.51  Complete
49996  49997      8880     4652        1409       21.43  Complete
49997  49998      3828     1572         574       24.59   Shipped
49998  49999      5471     4954        1551       16.46  Returned
49999  50000     18596     1691         584       79.17  Complete

                created_at           shipped_at         delivered_at  \
0      2023-05-24 05:04:44  2023-05-25 05:04:44  2023-05-30 05:04:44
1      2024-06-14 02:09:32  2024-06-16 02:09:32  2024-06-19 02:09:32
2      2023-06-16 03:42:36  2023-06-17 03:42:36  2023-06-25 03:42:36
3      2024-12-01 13:36:46  2024-12-03 13:36:46  2024-12-08 13:36:46
4      2024-08-21 13:24:24  2024-08-22 13:24:24  2024-08-29 13:24:24
...                    ...                  ...                  ...
49995  2024-04-07 06:30:10  2024-04-09 06:30:10  2024-04-13 06:30:10
49996  2024-05-02 13:08:00  2024-05-05 13:08:00  2024-05-14 13:08:00
49997  2023-02-27 19:26:28  2023-03-02 19:26:28                  NaN
49998  2023-05-08 03:01:16  2023-05-11 03:01:16  2023-05-14 03:01:16
49999  2024-08-09 06:01:46  2024-08-11 06:01:46  2024-08-19 06:01:46

               returned_at                                  product_name  \
0                      NaN                             Volcom Pro Active
1                      NaN                          Volcom Modern Shorts
2                      NaN                 Adidas Modern Socks & Hosiery
3                      NaN  Under Armour Regular Fit Jumpsuits & Rompers
4                      NaN                          Hurley Modern Skirts
...                    ...                                           ...
49995                  NaN                         Hanes Vintage Dresses
49996                  NaN                   Hurley Slim Fit Tops & Tees
49997                  NaN              Adidas Classic Blazers & Jackets
49998  2023-06-13 03:01:16         Polo Ralph Lauren Classic Accessories
49999                  NaN        Hugo Boss Original Suits & Sport Coats

                  category              brand department   cost gender  age  \
0                   Active             Volcom      Women  27.45      F   27
1                   Shorts             Volcom        Men  23.79      M   39
2          Socks & Hosiery             Adidas        Men   8.97      F   45
3      Jumpsuits & Rompers       Under Armour        Men  37.25      M   36
4                   Skirts             Hurley      Women  14.42      F   40
...                    ...                ...        ...    ...    ...  ...
49995              Dresses              Hanes      Women  16.96      M   32
49996          Tops & Tees             Hurley      Women  13.26      M   41
49997    Blazers & Jackets             Adidas      Women  16.41      F   30
49998          Accessories  Polo Ralph Lauren      Women  10.64      M   52
49999  Suits & Sport Coats          Hugo Boss        Men  36.29      F   58

              country         city traffic_source
0           Australia        Perth         Search
1              Mexico  Guadalajara         Search
2              Poland       Warsaw         Search
3               Spain      Seville        Organic
4      United Kingdom   Manchester        Organic
...               ...          ...            ...
49995   United States      Houston         Search
49996  United Kingdom        Leeds        Display
49997          France         Lyon       Facebook
49998  United Kingdom       London          Email
49999           Spain    Barcelona          Email

[50000 rows x 20 columns]

In [34]:
# ispremium

sales['is_premium'] = sales['sale_price'] > 100

sales.head(15)

,id,order_id,user_id,product_id,sale_price,status,created_at,shipped_at,delivered_at,returned_at,...,brand,department,cost,gender,age,country,city,traffic_source,marge,is_premium
0,1,2006,3641,533,37.47,Complete,2023-05-24 05:04:44,2023-05-25 05:04:44,2023-05-30 05:04:44,NaN,...,Volcom,Women,27.45,F,27,Australia,Perth,Search,10.02,False
1,2,19606,4289,1234,41.01,Complete,2024-06-14 02:09:32,2024-06-16 02:09:32,2024-06-19 02:09:32,NaN,...,Volcom,Men,23.79,M,39,Mexico,Guadalajara,Search,17.22,False
2,3,14234,973,409,15.67,Complete,2023-06-16 03:42:36,2023-06-17 03:42:36,2023-06-25 03:42:36,NaN,...,Adidas,Men,8.97,F,45,Poland,Warsaw,Search,6.70,False
3,4,14616,2136,67,75.15,Complete,2024-12-01 13:36:46,2024-12-03 13:36:46,2024-12-08 13:36:46,NaN,...,Under Armour,Men,37.25,M,36,Spain,Seville,Organic,37.90,False
4,5,7423,4007,1882,18.20,Complete,2024-08-21 13:24:24,2024-08-22 13:24:24,2024-08-29 13:24:24,NaN,...,Hurley,Women,14.42,F,40,United Kingdom,Manchester,Organic,3.78,False
5,6,7557,851,372,56.07,Complete,2023-06-19 23:00:28,2023-06-22 23:00:28,2023-06-29 23:00:28,NaN,...,Adidas,Women,28.70,M,21,China,Beijing,Search,27.37,False
6,7,7713,4096,1666,62.20,Complete,2023-10-02 08:39:14,2023-10-05 08:39:14,2023-10-11 08:39:14,NaN,...,True Religion,Men,51.87,F,18,Brazil,Salvador,Search,10.33,False
7,8,5654,984,1798,46.72,Complete,2024-10-09 11:30:16,2024-10-10 11:30:16,2024-10-18 11:30:16,NaN,...,Diesel,Men,25.90,F,29,United Kingdom,Leeds,Display,20.82,False
8,9,2616,4361,15,35.53,Shipped,2023-03-08 08:31:59,2023-03-11 08:31:59,NaN,NaN,...,True Religion,Women,22.82,F,35,Germany,Frankfurt,Facebook,12.71,False
9,10,1478,3060,1300,49.57,Shipped,2023-05-01 22:06:29,2023-05-04 22:06:29,NaN,NaN,...,Columbia,Men,28.14,M,48,Poland,Łódź,Organic,21.43,False
10,11,3795,1534,65,39.27,Complete,2024-12-01 15:44:35,2024-12-02 15:44:35,2024-12-08 15:44:35,NaN,...,Tommy Hilfiger,Men,25.60,F,26,Germany,Munich,Organic,13.67,False
11,12,7564,207,1170,15.14,Complete,2023-10-11 04:14:20,2023-10-13 04:14:20,2023-10-22 04:14:20,NaN,...,Volcom,Women,7.16,F,28,Austria,Salzburg,Search,7.98,False
12,13,12632,762,196,13.70,Shipped,2024-03-22 10:42:08,2024-03-24 10:42:08,NaN,NaN,...,Hurley,Men,5.33,M,54,United States,Miami,Email,8.37,False
13,14,16216,219,1982,21.74,Complete,2024-09-28 21:40:40,2024-09-30 21:40:40,2024-10-08 21:40:40,NaN,...,Lacoste,Men,11.84,F,56,Brazil,Salvador,Display,9.90,False
14,15,643,3231,175,216.32,Complete,2023-10-13 04:49:24,2023-10-14 04:49:24,2023-10-18 04:49:24,NaN,...,Calvin Klein,Women,99.79,M,43,United States,Denver,Search,116.53,True

In [35]:
# 2. Convertissez created_at et extrayez le mois
sales['month'] = pd.to_datetime(sales['created_at']).dt.month

sales.head(15)

,id,order_id,user_id,product_id,sale_price,status,created_at,shipped_at,delivered_at,returned_at,...,department,cost,gender,age,country,city,traffic_source,marge,is_premium,month
0,1,2006,3641,533,37.47,Complete,2023-05-24 05:04:44,2023-05-25 05:04:44,2023-05-30 05:04:44,NaN,...,Women,27.45,F,27,Australia,Perth,Search,10.02,False,5
1,2,19606,4289,1234,41.01,Complete,2024-06-14 02:09:32,2024-06-16 02:09:32,2024-06-19 02:09:32,NaN,...,Men,23.79,M,39,Mexico,Guadalajara,Search,17.22,False,6
2,3,14234,973,409,15.67,Complete,2023-06-16 03:42:36,2023-06-17 03:42:36,2023-06-25 03:42:36,NaN,...,Men,8.97,F,45,Poland,Warsaw,Search,6.70,False,6
3,4,14616,2136,67,75.15,Complete,2024-12-01 13:36:46,2024-12-03 13:36:46,2024-12-08 13:36:46,NaN,...,Men,37.25,M,36,Spain,Seville,Organic,37.90,False,12
4,5,7423,4007,1882,18.20,Complete,2024-08-21 13:24:24,2024-08-22 13:24:24,2024-08-29 13:24:24,NaN,...,Women,14.42,F,40,United Kingdom,Manchester,Organic,3.78,False,8
5,6,7557,851,372,56.07,Complete,2023-06-19 23:00:28,2023-06-22 23:00:28,2023-06-29 23:00:28,NaN,...,Women,28.70,M,21,China,Beijing,Search,27.37,False,6
6,7,7713,4096,1666,62.20,Complete,2023-10-02 08:39:14,2023-10-05 08:39:14,2023-10-11 08:39:14,NaN,...,Men,51.87,F,18,Brazil,Salvador,Search,10.33,False,10
7,8,5654,984,1798,46.72,Complete,2024-10-09 11:30:16,2024-10-10 11:30:16,2024-10-18 11:30:16,NaN,...,Men,25.90,F,29,United Kingdom,Leeds,Display,20.82,False,10
8,9,2616,4361,15,35.53,Shipped,2023-03-08 08:31:59,2023-03-11 08:31:59,NaN,NaN,...,Women,22.82,F,35,Germany,Frankfurt,Facebook,12.71,False,3
9,10,1478,3060,1300,49.57,Shipped,2023-05-01 22:06:29,2023-05-04 22:06:29,NaN,NaN,...,Men,28.14,M,48,Poland,Łódź,Organic,21.43,False,5
10,11,3795,1534,65,39.27,Complete,2024-12-01 15:44:35,2024-12-02 15:44:35,2024-12-08 15:44:35,NaN,...,Men,25.60,F,26,Germany,Munich,Organic,13.67,False,12
11,12,7564,207,1170,15.14,Complete,2023-10-11 04:14:20,2023-10-13 04:14:20,2023-10-22 04:14:20,NaN,...,Women,7.16,F,28,Austria,Salzburg,Search,7.98,False,10
12,13,12632,762,196,13.70,Shipped,2024-03-22 10:42:08,2024-03-24 10:42:08,NaN,NaN,...,Men,5.33,M,54,United States,Miami,Email,8.37,False,3
13,14,16216,219,1982,21.74,Complete,2024-09-28 21:40:40,2024-09-30 21:40:40,2024-10-08 21:40:40,NaN,...,Men,11.84,F,56,Brazil,Salvador,Display,9.90,False,9
14,15,643,3231,175,216.32,Complete,2023-10-13 04:49:24,2023-10-14 04:49:24,2023-10-18 04:49:24,NaN,...,Women,99.79,M,43,United States,Denver,Search,116.53,True,10

In [ ]:
# Taux marges
sales['taux_marge'] = sales['marge'] / sales['sale_price'] * 100

sales.head(15)

,id,order_id,user_id,product_id,sale_price,status,created_at,shipped_at,delivered_at,returned_at,...,cost,gender,age,country,city,traffic_source,marge,is_premium,month,taux_marge
0,1,2006,3641,533,37.47,Complete,2023-05-24 05:04:44,2023-05-25 05:04:44,2023-05-30 05:04:44,NaN,...,27.45,F,27,Australia,Perth,Search,10.02,False,5,26.741393
1,2,19606,4289,1234,41.01,Complete,2024-06-14 02:09:32,2024-06-16 02:09:32,2024-06-19 02:09:32,NaN,...,23.79,M,39,Mexico,Guadalajara,Search,17.22,False,6,41.989759
2,3,14234,973,409,15.67,Complete,2023-06-16 03:42:36,2023-06-17 03:42:36,2023-06-25 03:42:36,NaN,...,8.97,F,45,Poland,Warsaw,Search,6.70,False,6,42.756860
3,4,14616,2136,67,75.15,Complete,2024-12-01 13:36:46,2024-12-03 13:36:46,2024-12-08 13:36:46,NaN,...,37.25,M,36,Spain,Seville,Organic,37.90,False,12,50.432468
4,5,7423,4007,1882,18.20,Complete,2024-08-21 13:24:24,2024-08-22 13:24:24,2024-08-29 13:24:24,NaN,...,14.42,F,40,United Kingdom,Manchester,Organic,3.78,False,8,20.769231
5,6,7557,851,372,56.07,Complete,2023-06-19 23:00:28,2023-06-22 23:00:28,2023-06-29 23:00:28,NaN,...,28.70,M,21,China,Beijing,Search,27.37,False,6,48.813983
6,7,7713,4096,1666,62.20,Complete,2023-10-02 08:39:14,2023-10-05 08:39:14,2023-10-11 08:39:14,NaN,...,51.87,F,18,Brazil,Salvador,Search,10.33,False,10,16.607717
7,8,5654,984,1798,46.72,Complete,2024-10-09 11:30:16,2024-10-10 11:30:16,2024-10-18 11:30:16,NaN,...,25.90,F,29,United Kingdom,Leeds,Display,20.82,False,10,44.563356
8,9,2616,4361,15,35.53,Shipped,2023-03-08 08:31:59,2023-03-11 08:31:59,NaN,NaN,...,22.82,F,35,Germany,Frankfurt,Facebook,12.71,False,3,35.772587
9,10,1478,3060,1300,49.57,Shipped,2023-05-01 22:06:29,2023-05-04 22:06:29,NaN,NaN,...,28.14,M,48,Poland,Łódź,Organic,21.43,False,5,43.231793
10,11,3795,1534,65,39.27,Complete,2024-12-01 15:44:35,2024-12-02 15:44:35,2024-12-08 15:44:35,NaN,...,25.60,F,26,Germany,Munich,Organic,13.67,False,12,34.810288
11,12,7564,207,1170,15.14,Complete,2023-10-11 04:14:20,2023-10-13 04:14:20,2023-10-22 04:14:20,NaN,...,7.16,F,28,Austria,Salzburg,Search,7.98,False,10,52.708058
12,13,12632,762,196,13.70,Shipped,2024-03-22 10:42:08,2024-03-24 10:42:08,NaN,NaN,...,5.33,M,54,United States,Miami,Email,8.37,False,3,61.094891
13,14,16216,219,1982,21.74,Complete,2024-09-28 21:40:40,2024-09-30 21:40:40,2024-10-08 21:40:40,NaN,...,11.84,F,56,Brazil,Salvador,Display,9.90,False,9,45.538178
14,15,643,3231,175,216.32,Complete,2023-10-13 04:49:24,2023-10-14 04:49:24,2023-10-18 04:49:24,NaN,...,99.79,M,43,United States,Denver,Search,116.53,True,10,53.869268

## Exercice 3.2 — Le Nettoyeur de Noms
Chargez `../01_data/raw/thelook_products.csv`.
1. Mettez la colonne `name` en title case
2. Extrayez le premier mot du nom dans une colonne `marque`
3. Combien de produits contiennent le mot 'Slim' ?

In [29]:
# 1 et 2. Title case + extraction marque
products['name'] = products['name'].str.title()

# extraction de la marque
products['brand'] = products['name'].str.split(' ').str[0]

products.head(10)

,id,name,category,department,cost,retail_price_euro,reference,distribution_center_id,marge,ref_id,taux_marge,brand
0,1,Tommy Hilfiger Regular Fit Underwear,Underwear,Women,6.57,10.31,SKU-00001,5,3.74,SKU-000011,36.275461,Tommy
1,2,Hurley Pro Shorts,Shorts,Women,20.85,37.55,SKU-00002,6,16.70,SKU-000022,44.474035,Hurley
2,3,Columbia Sport Tops & Tees,Tops & Tees,Men,21.34,44.52,SKU-00003,9,23.18,SKU-000033,52.066487,Columbia
3,4,Volcom Classic Leggings,Leggings,Women,14.98,42.24,SKU-00004,2,27.26,SKU-000044,64.535985,Volcom
4,5,Hurley Urban Outerwear & Coats,Outerwear & Coats,Women,89.58,149.11,SKU-00005,5,59.53,SKU-000055,39.923546,Hurley
5,6,Volcom Original Dresses,Dresses,Women,60.37,157.91,SKU-00006,10,97.54,SKU-000066,61.769362,Volcom
6,7,Lacoste Original Underwear,Underwear,Women,4.72,13.83,SKU-00007,3,9.11,SKU-000077,65.871294,Lacoste
7,8,Lacoste Comfort Tops & Tees,Tops & Tees,Women,16.82,27.19,SKU-00008,4,10.37,SKU-000088,38.139022,Lacoste
8,9,Levi'S Modern Shorts,Shorts,Women,24.62,49.23,SKU-00009,9,24.61,SKU-000099,49.989844,Levi'S
9,10,Diesel Essential Swim,Swim,Women,7.77,20.62,SKU-00010,8,12.85,SKU-0001010,62.318138,Diesel

In [31]:
# nbre de mot de produits contenant 'slim'
products['name'] = products['name'].str.contains('Slim')

products

AttributeError: Can only use .str accessor with string values, not boolean

In [ ]:
# 3. Comptez les produits 'Sport'
# Votre code ici

## Exercice 3.3 — L'analyse temporel
Chargez `../01_data/raw/thelook_orders.csv`.
1. Convertissez created_at, shipped_at, delivered_at en datetime
2. Créez `delai_livraison` = delivered_at - created_at (en jours)
3. Quel est le délai moyen ? Varie-t-il selon le jour de la semaine ?

In [ ]:
# 1. Conversion des dates
# Votre code ici

In [ ]:
# 2. Calcul du délai
# Votre code ici

In [ ]:
# 3. Délai moyen et variation par jour
# Votre code ici